apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extensionlib.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- include "extensionlib.labels" (list .) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "extensionlib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "extensionlib.selectorLabels" . | nindent 8 }}
        {{- include "extensionlib.labels" (list .) | nindent 8 }}
        {{- range $key, $value := .Values.extraLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: extension
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            {{- include "extensionlib.deployment.env" (list .) | nindent 12 }}
            - name: STEADYBIT_EXTENSION_KONG_INSTANCE_0_NAME
              value: {{ .Values.kong.name | quote }}
            - name: STEADYBIT_EXTENSION_KONG_INSTANCE_0_ORIGIN
              value: {{ .Values.kong.origin | quote }}
            {{- if and (.Values.kong.headerKey) (.Values.kong.headerValue) }}
            - name: STEADYBIT_EXTENSION_KONG_INSTANCE_0_HEADER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "extensionlib.names.name" . }}-header
                  key: key
            - name: STEADYBIT_EXTENSION_KONG_INSTANCE_0_HEADER_VALUE
              valueFrom:
                secretKeyRef:
                  name: {{ include "extensionlib.names.name" . }}-header
                  key: value
            {{- end }}
            {{- with .Values.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "extensionlib.deployment.volumeMounts" (list .) | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8085
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8085
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        {{- include "extensionlib.deployment.volumes" (list .) | nindent 8 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
