{{- if and (.Values.kong.headerKey) (.Values.kong.headerValue) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "extensionlib.names.name" . }}-header
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  key: {{ .Values.kong.headerKey | b64enc | quote }}
  value: {{ .Values.kong.headerValue | b64enc | quote }}
{{- end }}
