apiVersion: v1
kind: Namespace
metadata:
  name: steadybit-extension
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: steadybit-extension-kong
  namespace: steadybit-extension
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steadybit-extension-kong
  namespace: steadybit-extension
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: steadybit-extension-kong
  template:
    metadata:
      labels:
        app.kubernetes.io/name: steadybit-extension-kong
    spec:
      containers:
        - image: ghcr.io/steadybit/extension-kong:main
          imagePullPolicy: Always
          name: steadybit-extension-kong
          env:
            - name: STEADYBIT_EXTENSION_KONG_INSTANCE_0_NAME
              value: "default"
            - name: STEADYBIT_EXTENSION_KONG_INSTANCE_0_ORIGIN
              value: "http://kong:8001"
            - name: STEADYBIT_LOG_LEVEL
              value: "INFO"
      serviceAccountName: steadybit-extension-kong
---
apiVersion: v1
kind: Service
metadata:
  name: steadybit-extension-kong
  namespace: steadybit-extension
spec:
  selector:
    app.kubernetes.io/name: steadybit-extension-kong
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
